apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-order-api
  namespace: default
  labels:
    app: deployment-order-api
spec:
  selector:
    matchLabels:
      app: "order-api"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "order-api"
    spec:
      containers:
        - name: "order-api"
          image: acdmanderson/order-api:$DOCKER_TAG
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
            requests:
              cpu: "0.2"
              memory: 200Mi
          readinessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 15
          livenessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - containerPort: 9002
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: db_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-order-api-config
                  key: DB_NAME
        
